Traceback (most recent call last):
  File "jPCA/KPCA/HumanGenomeTest/MyVersion/gram_conversion_txt_to_npy.py", line 6, in <module>
    GRAM = np.loadtxt('/hpc/hers_en/fsimoes/logs/objects/jaccard_gram_R_eur_rare_with_{}_vars.txt'.format(nvars), skiprows=1)
  File "/home/hers_en/fsimoes/miniconda3/lib/python3.7/site-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/home/hers_en/fsimoes/miniconda3/lib/python3.7/site-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/home/hers_en/fsimoes/miniconda3/lib/python3.7/site-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: /hpc/hers_en/fsimoes/logs/objects/jaccard_gram_R_eur_rare_with_500000_vars.txt not found.

real	0m1.313s
user	0m0.199s
sys	0m0.072s
